export const T = {
  en: {
    login:"Login",register:"Register",storeName:"Store Name",ownerName:"Owner Name",mobile:"Mobile Number",password:"Password",address:"Address",lang:"Language",loginBtn:"Login →",registerBtn:"Create Account →",
    home:"Home",products:"Products",order:"Order",details:"Details",history:"History",
    gm:"Good Morning",ga:"Good Afternoon",ge:"Good Evening",
    todayCol:"Today's Business",totalRev:"Total Revenue",pending:"Pending Amount",activeOrd:"Active Orders",availStock:"Available Stock",
    stock:"Stock Overview",activeRent:"Active Rentals",newOrd:"+ New Order",
    addProd:"Add Product",editProd:"Edit Product",prodName:"Product Name",totalQty:"Total Qty",rentDay:"Rent/Day ₹",deposit:"Deposit ₹",opt:"Optional",del:"Delete",noProd:"No Products",addFirst:"Add your first product",
    custDet:"Customer Details",name:"Name",event:"Event Type",notes:"Notes",selProd:"Select Products",
    startDate:"Start Date",createBook:"Create Booking ✓",created:"Booking Created!",shareWA:"WhatsApp",
    dailyRent:"Daily Rent",newOrdBtn:"+ New Order",goHome:"← Home",
    orderDet:"Order Details",search:"Search customer...",all:"All",active:"Active",returned:"Returned",paid:"Paid",unpaid:"Unpaid",
    orders:"orders",items:"Items",retBill:"Return & Billing",retDate:"Return Date",days:"Days",day:"Day",
    specRate:"Special Rate 50%",custDisc:"Discount ₹",damages:"Damages",addDmg:"+ Add Damage",
    dmgProd:"Damaged Product",dmgQty:"Damaged Qty",dmgRate:"Rate/Unit ₹",dmgAmt:"Damage Amount",
    actions:"Status & Actions",markRet:"Mark Returned",markPaid:"Mark Paid ✓",
    remind:"Send WhatsApp Reminder",
    waInv:"WhatsApp Bill",dlPdf:"Download PDF",billSum:"Bill Summary",disc:"Discount",
    dmgChg:"Damage Charges",total:"Total",
    hist:"History",monthly:"Monthly",yearly:"Yearly",expWA:"Export WhatsApp",expPDF:"Export PDF",
    bookings:"bookings",noBk:"No bookings",
    wedding:"Wedding",birthday:"Birthday",temple:"Temple",house:"House Function",shop:"Shop Opening",engage:"Engagement",reception:"Reception",other:"Other",
    upload:"Tap to upload image",qty:"Qty",free:"free",out:"rented",avail:"Available",rented:"Rented",perDay:"/day",
    delOrder:"Delete Order",delConfirm:"Delete this order permanently?",cancel:"Cancel",
    retPaid:"Returned & Paid ✓",retUnpaid:"Returned & Unpaid",activeUnpaid:"Active & Unpaid",activePaid:"Active & Paid",
    inv:"Invalid credentials!",allReq:"All fields required!",mobEx:"Mobile already registered!",
    balance:"Balance",imgProd:"Product Image",
    profile:"Profile",staffMembers:"Staff Members",addStaff:"+ Add Staff",vip:"VIP Order",
    generatedBy:"Generated By",signature:"Signature",save:"Save",deleted:"Deleted",restore:"Restore",
    membersMax:"Max 5 Members",owner:"Store Owner",ownerSign:"Owner Signature",
    delStaff:"Delete Staff",noStaff:"No staff added"
  },
  ta: {
    login:"உள்நுழை",register:"பதிவு செய்",storeName:"கடை பெயர்",ownerName:"உரிமையாளர்",mobile:"மொபைல் எண்",password:"கடவுச்சொல்",address:"முகவரி",lang:"மொழி",loginBtn:"உள்நுழை →",registerBtn:"கணக்கு உருவாக்கு →",
    home:"முகப்பு",products:"பொருட்கள்",order:"ஆர்டர்",details:"விவரம்",history:"வரலாறு",
    gm:"காலை வணக்கம்",ga:"மதிய வணக்கம்",ge:"மாலை வணக்கம்",
    todayCol:"இன்று வணிகம்",totalRev:"மொத்த வருவாய்",pending:"நிலுவை தொகை",activeOrd:"செயலில் உள்ளவை",availStock:"இருப்பு பொருட்கள்",
    stock:"பொருள் நிலை",activeRent:"வாடகையில் உள்ளவை",newOrd:"+ புதிய ஆர்டர்",
    addProd:"பொருள் சேர்",editProd:"பொருள் திருத்து",prodName:"பொருள் பெயர்",totalQty:"மொத்த எண்",rentDay:"வாடகை/நாள் ₹",deposit:"வைப்பு ₹",opt:"விருப்பம்",del:"நீக்கு",noProd:"பொருட்கள் இல்லை",addFirst:"முதல் பொருளைச் சேர்க்கவும்",
    custDet:"வாடிக்கையாளர் விவரம்",name:"பெயர்",event:"நிகழ்வு வகை",notes:"குறிப்பு",selProd:"பொருட்கள் தேர்வு",
    startDate:"தொடக்க தேதி",createBook:"புக்கிங் செய் ✓",created:"புக்கிங் உருவாக்கப்பட்டது!",shareWA:"வாட்ஸ்அப்",
    dailyRent:"தினசரி வாடகை",newOrdBtn:"+ புதிய ஆர்டர்",goHome:"← முகப்பு",
    orderDet:"ஆர்டர் விவரம்",search:"வாடிக்கையாளர் தேடு...",all:"அனைத்தும்",active:"செயலில்",returned:"திரும்பியது",paid:"செலுத்தியது",unpaid:"நிலுவை",
    orders:"ஆர்டர்கள்",items:"பொருட்கள்",retBill:"திருப்பி & பில்",retDate:"திருப்பும் தேதி",days:"நாட்கள்",day:"நாள்",
    specRate:"சிறப்பு விலை 50%",custDisc:"தள்ளுபடி ₹",damages:"சேதம்",addDmg:"+ சேதம் சேர்",
    dmgProd:"சேதமான பொருள்",dmgQty:"சேத எண்",dmgRate:"ஒன்றுக்கு ₹",dmgAmt:"சேத தொகை",
    actions:"நிலை & செயல்கள்",markRet:"திரும்பியது ✓",markPaid:"பணம் வாங்கியது ✓",
    remind:"வாட்ஸ்அப் நினைவூட்டல் அனுப்பு",
    waInv:"வாட்ஸ்அப் பில்",dlPdf:"PDF பதிவிறக்கு",billSum:"பில் சுருக்கம்",disc:"தள்ளுபடி",
    dmgChg:"சேத கட்டணம்",total:"மொத்தம்",
    hist:"வரலாறு",monthly:"மாதம்",yearly:"வருடம்",expWA:"வாட்ஸ்அப்",expPDF:"PDF",
    bookings:"புக்கிங்கள்",noBk:"புக்கிங் இல்லை",
    wedding:"திருமணம்",birthday:"பிறந்தநாள்",temple:"கோவில் விழா",house:"வீட்டு விழா",shop:"கடை திறப்பு",engage:"நிச்சயதார்த்தம்",reception:"வரவேற்பு",other:"மற்றவை",
    upload:"படம் பதிவேற்ற தட்டவும்",qty:"எண்",free:"கிடைக்கும்",out:"வாடகையில்",avail:"கிடைக்கும்",rented:"வாடகை",perDay:"/நாள்",
    delOrder:"ஆர்டர் நீக்கு",delConfirm:"இந்த ஆர்டரை நீக்கவா?",cancel:"ரத்து",
    retPaid:"திரும்பியது & பணம் ✓",retUnpaid:"திரும்பியது & நிலுவை",activeUnpaid:"செயலில் & நிலுவை",activePaid:"செயலில் & பணம் ✓",
    inv:"தவறான தகவல்!",allReq:"அனைத்தும் தேவை!",mobEx:"மொபைல் பதிவு உள்ளது!",
    balance:"மீதி",imgProd:"பொருள் படம்",
    profile:"சுயவிவரம்",staffMembers:"பணியாளர்கள்",addStaff:"+ பணியாளர் சேர்",vip:"விஐபி",
    generatedBy:"பில் உருவாக்கியவர்",signature:"கையொப்பம்",save:"சேமி",deleted:"நீக்கப்பட்டது",restore:"மீட்டமை",
    membersMax:"அதிகபட்சம் 5",owner:"உரிமையாளர்",ownerSign:"உரிமையாளர் கையொப்பம்",
    delStaff:"பணியாளரை நீக்கு",noStaff:"பணியாளர்கள் இல்லை"
  }
};

export const getGreetKey = () => {
  const h = new Date().getHours();
  return h < 12 ? 'gm' : h < 17 ? 'ga' : 'ge';
};

export const EVENTS = ['wedding','birthday','temple','house','shop','engage','reception','other'];
